name: Release Rust Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          allow-missing-changelog: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v2

      - name: Build and Upload Binaries
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: zk-psi-setup
          target: x86_64-unknown-linux-gnu
          archive: zk-psi-setup-x86_64-linux-${{ github.ref_name }}
          include: LICENSE,README.md
          checksum: sha256,sha512
          ref: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Upload CLI
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: zk-psi-cli
          target: x86_64-unknown-linux-gnu
          archive: zk-psi-cli-x86_64-linux-${{ github.ref_name }}
          include: LICENSE,README.md
          checksum: sha256,sha512
          ref: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
