name: Release Rust Binary

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  BINARIES: "zk-psi-setup zk-psi-cli"
  TAG: ${{ github.ref_name }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v2

      - name: Build Binaries
        run: |
          mkdir -p artifacts
          for bin in $BINARIES; do
            cargo build --release --bin $bin --target x86_64-unknown-linux-gnu
            cp target/x86_64-unknown-linux-gnu/release/$bin artifacts/${bin}-x86_64-linux-${TAG}
          done
          cp LICENSE README.md artifacts/

      - name: Generate Checksums
        run: |
          cd artifacts
          sha256sum * > SHA256SUMS
          sha512sum * > SHA512SUMS
          cat SHA256SUMS

      - name: Package Artifacts
        run: |
          cd artifacts
          tar -czf zk-psi-linux-x86_64-${TAG}.tar.gz * 

      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-gh-release-action.outputs.upload_url }}
          asset_path: artifacts/zk-psi-linux-x86_64-${TAG}.tar.gz
          asset_name: zk-psi-linux-x86_64-${TAG}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Checksums
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-gh-release-action.outputs.upload_url }}
          asset_path: artifacts/SHA256SUMS
          asset_name: SHA256SUMS
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Checksums
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-gh-release-action.outputs.upload_url }}
          asset_path: artifacts/SHA512SUMS
          asset_name: SHA512SUMS
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
